# Generated by Django 3.2.5 on 2021-07-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_date_started'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='date_started',
            new_name='last_modified',
        ),
    ]
