# Generated by Django 3.2.5 on 2021-07-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='new_message_count',
            field=models.IntegerField(default=0),
        ),
    ]
