# Generated by Django 3.2.3 on 2021-06-02 13:19

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='user-images/download.jpg', upload_to='user-images/')),
                ('username', models.CharField(max_length=255)),
                ('user_bio', models.TextField(blank=True, default='Hi, welcome to my profile!')),
                ('is_tutor', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('tutor_whatsapp', models.IntegerField(blank=True, null=True)),
                ('tutor_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('aggregate_star', models.FloatField(blank=True, null=True)),
                ('duration_classes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]), blank=True, null=True, size=None)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, null=True, size=None)),
                ('total_tutor_reviews', models.IntegerField(default=0)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
