# Generated by Django 3.2.3 on 2021-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0005_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
