# Generated by Django 3.2.3 on 2021-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0005_alter_profile_duration_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutor_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
