# Generated by Django 3.2.3 on 2021-06-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0006_auto_20210601_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tutor_contact',
        ),
    ]
