# Generated by Django 3.2.5 on 2021-07-11 12:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0006_profile_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, default=list, size=None),
        ),
    ]
