# Generated by Django 3.2.3 on 2021-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0006_auto_20210601_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tutor_telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutor_whatsapp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tutor_contact',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
