# Generated by Django 3.2.3 on 2021-06-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0007_auto_20210601_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tutor_contact',
        ),
    ]
