# Generated by Django 3.2.5 on 2021-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0007_alter_profile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tuition_rates',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
