# Generated by Django 3.2.5 on 2021-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0008_profile_tuition_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qualifications',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
