# Generated by Django 3.2.3 on 2021-06-02 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=70)),
                ('video_description', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('asset_id', models.CharField(max_length=200)),
                ('playback_id', models.CharField(max_length=200)),
                ('duration', models.FloatField()),
                ('policy', models.CharField(max_length=100)),
                ('created_at', models.IntegerField()),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='userProfiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='VideoLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_liking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_video', to='userVideos.video')),
            ],
        ),
    ]
