# Generated by Django 3.2.4 on 2021-06-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userVideos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolikes',
            old_name='video',
            new_name='liked_video',
        ),
        migrations.AlterField(
            model_name='videolikes',
            name='user_liking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VideoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('date_comment', models.DateField(auto_now_add=True)),
                ('date_comment_edited', models.DateField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
                ('commented_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_video', to='userVideos.video')),
                ('user_commenting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commenting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
