# Generated by Django 3.2.4 on 2021-06-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userVideos', '0002_auto_20210607_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='numOfComments',
            field=models.IntegerField(default=0),
        ),
    ]
