# Generated by Django 3.2.4 on 2021-06-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userVideos', '0003_auto_20210607_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='numOfComments',
            new_name='num_of_comments',
        ),
    ]
