# Generated by Django 3.2.4 on 2021-06-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0005_profile_location'),
        ('userVideos', '0005_auto_20210608_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomments',
            name='user_commenting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_commenting', to='userProfiles.profile'),
        ),
    ]
