# Generated by Django 3.2.3 on 2021-06-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userVideos', '0006_alter_videocomments_user_commenting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_description',
            field=models.CharField(max_length=6000),
        ),
    ]
