# Generated by Django 3.2.3 on 2021-06-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.FloatField()),
                ('review_title', models.CharField(max_length=150)),
                ('review_essay', models.TextField()),
                ('date_review', models.DateField(auto_now_add=True)),
                ('date_review_edited', models.DateField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='userProfiles.profile')),
                ('tutor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='userProfiles.profile')),
            ],
        ),
    ]
