# Generated by Django 3.2.5 on 2021-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject_taken',
            field=models.CharField(default='Biology', max_length=55),
            preserve_default=False,
        ),
    ]
