# Generated by Django 3.2.5 on 2021-07-20 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0002_review_subject_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='subject_taken',
        ),
        migrations.AddField(
            model_name='review',
            name='subjects_taken',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=55), blank=True, default=list, size=None),
        ),
    ]
