# Generated by Django 3.2.5 on 2021-07-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userReviews', '0003_auto_20210720_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='subjects_taken',
            new_name='review_subject',
        ),
    ]
